### PR TITLE
[Currency] Add event for currency formatting

### PR DESCRIPTION
**Pull request by mysliwietzflorian**
Proposal: Add an event before any currency is formatted to add flexibility for the formatting patterns. Code could still be improved (Add custom event model, define event name), but do we want this change?

Our use-case is a new Swiss tenant, where two different common currency formats exist:
- `CHF 10.50` for values with Rappen value != 0 OR
- `110.–` for values with Rappen value == 0

The change in this PR allows us to write something like inside an EventSubscriber:
```PHP
$value = (string)$event->getArgument('value');
if (str_ends_with($value, '.00')) {
    $event->setArgument('pattern', '#,##0.–');
}
```

### CODE REVIEW

**Comment by NiklasBr** [comment]
Isn't this already possible using https://pimcore.com/docs/platform/Pimcore/Multi_Language_i18n/Formatting_Service?

**Comment by mysliwietzflorian** [comment]
@NiklasBr 
> Isn't this already possible using https://pimcore.com/docs/platform/Pimcore/Multi_Language_i18n/Formatting_Service?

Maybe I have overlooked something. As far as I have tried you can set a pattern for a locale, but you cannot have different patterns depending on the value. In my example above I use the default Swiss format, but change the pattern if a specific value occurs (`'#,##0.–'`).

I could not figure out a way to do this. ;)

**Comment by NiklasBr** [comment]
There is a `patthern` argument you can use though.

https://github.com/pimcore/pimcore/blob/ce6cff09c03044f777f943d59ae730a6eb6cb924/lib/Localization/IntlFormatter.php#L202-L217

**Comment by mysliwietzflorian** [comment]
> There is a `patthern` argument you can use though.

Agree. I see your point. That means I'd need to check before the call of `formatCurrency`. Should work for me. ;)

**Pull request closed without merging**
