### PR TITLE
Array flip makes voucher strings to int

### PR DESCRIPTION
**Pull request by Daniel-Ateles**
When adding voucher-tokens that are all numbers the array_flip function will make the values to int's so we need to cast to string in OrderManager.
We also need to cast to int when reading configuration->getUsages() because it returns string.

### CODE REVIEW

**Comment by fashxp** [comment]
thx very much. could you please rebase to 1.0 branch

**Comment by fashxp** [comment]
@Daniel-Ateles :ping_pong:

**Comment by Daniel-Ateles** [comment]
> @Daniel-Ateles 🏓

I have to admit I'm not sure how to rebase to 1.0 branch. Can one do it directly here from github?

**Comment by fashxp** [comment]
> > @Daniel-Ateles 🏓
> 
> I have to admit I'm not sure how to rebase to 1.0 branch. Can one do it directly here from github?

sadly not, as it would contain the 1.x commits. needs to be done via git ... checkout, rebase branch to 1.0 and then force push the branch (to make sure the 1.x commits are gone). and then we can rebase the PR here it github.

**Comment by fashxp** [comment]
merged and cherry-picked https://github.com/pimcore/ecommerce-framework-bundle/commit/49109e84242d335fa7175159305a8f0cc0837fa0

**Pull request merged**
