### PR TITLE
[BUGFIX] Process two-dimensional arrays from DefaultBrickGetterSequen…

### LINKED ISSUE #150: [Bug]: Array to string conversion while product indexing
### Expected behavior

Product indexer works with all provided getters (also DefaultBrickGetterSequenceToMultiselect)

### Actual behavior

If in index_service configuration, the `getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequenceToMultiselect` is set, the exception is thrown:

> Exception in IndexService: ErrorException: Warning: Array to string conversion in /var/www/html/app/site/vendor/pimcore/ecommerce-framework-bundle/src/IndexService/Worker/AbstractWorker.php

The DefaultBrickGetterSequenceToMultiselect getter returns a multidimensional array, which cannot be processed in implode() function in AbstractWorker->convertArray()

### Steps to reproduce

- Set `getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequenceToMultiselect` in index_service configuration
- Run indexer

### PR DESCRIPTION
**Pull request by 80Quattro**
…ceToMultiselect

Closes #150

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by fashxp** [comment]
can you please rebase to 1.0, thx.

**Comment by 80Quattro** [comment]
done

**Comment by fashxp** [comment]
@80Quattro hmm, didn't work. when I change the base, I get lot of additional commits into that PR.
You need to rebase to 1.0 and then force-push to your branch. This should hopefully work...

**Comment by fashxp** [comment]
@80Quattro :ping_pong:

**Comment by 80Quattro** [comment]
@fashxp I apologize for the delayed response. I struggled with it. I've created a new pull request that merges with branch 1.0. Hope it helps

[https://github.com/pimcore/ecommerce-framework-bundle/pull/167](https://github.com/pimcore/ecommerce-framework-bundle/pull/167)

**Pull request closed without merging**
