### PR TITLE
[BUGFIX] Don't trim value if it's null

### LINKED ISSUE #144: [Bug]: SelectFromMultiSelect -> trim(null)
### Expected behavior

SelectFromMultiSelect works also if $value == AbstractFilterType::EMPTY_STRING

### Actual behavior

trim(): Argument #1 ($string) must be of type string, null given

An Exception is thrown if $value == AbstractFilterType::EMPTY_STRING in SelectFromMultiSelect

SelectFromMultiSelect.php, line 66 -> There is assigned null to $value,

then, in line 72, function trim($value) is called -> trim(null) is not allowed in PHP: [doku](https://www.php.net/manual/en/function.trim.php)

### Steps to reproduce

-

### PR DESCRIPTION
**Pull request by 80Quattro**
Closes #144

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by bluvulture** [comment]
Hey @80Quattro 

Could you plase sign cla and then re-trigger the check?

Tnx

**Comment by 80Quattro** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 80Quattro** [comment]
recheck

**Comment by 80Quattro** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 80Quattro** [comment]
recheck

**Pull request merged**
