### PR TITLE
SelectCategory.php: Cast $value to string

### PR DESCRIPTION
**Pull request by MarkTro**
$value can set with an int value (line 73) by "getId()". Trim throws in strict mode an error, if it doesn't get a string. Therefore we need to cast $value to a string.

### CODE REVIEW

**Comment by MarkTro** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fashxp** [comment]
thx very much.

**Comment by fashxp** [comment]
but could you please rebase to 1.0 branch

**Comment by fashxp** [comment]
sadly that didn't work out. you need to rebase (not merge) your local branch to 1.0 and then force-push to remote.

**Comment by MarkTro** [comment]
Hey @fashxp ,
I tried to rebase the branch, but there suddenly some commit in it which wasn't mine. Therefore I created a new MR based on branch 1.0: 
https://github.com/pimcore/ecommerce-framework-bundle/pull/156

I close this one.

**Comment by fashxp** [comment]
thx very much

**Pull request closed without merging**
